version: '2'
services:
  discoveryservice:
    image: 'aista/eureka'
    ports:
      - "8761:8761"
    networks:
      - banking-microservices-example_bank
  edgeservice:
    build: 'edgeservice/'
    ports:
      - "8080:8080"
    networks:
      - banking-microservices-example_bank
  mongo:
    image: 'mongo:3.4.1'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'
    networks:
      - banking-microservices-example_bank
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - banking-microservices-example_bank
  configurationservice:
    image: aista/configuration-service
    ports:
      - '8888:8080'
    depends_on:
      - discoveryservice
    networks:
      - banking-microservices-example_bank

networks:
  banking-microservices-example_bank:
    driver: bridge

volumes:
  mongo:
